# Generated by Django 6.0.3 on 2026-03-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_api', '0002_remove_project_members_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
