# Generated by Django 6.0.3 on 2026-03-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_api', '0003_alter_comment_content_alter_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
